name: Flutter Check

on:
  push:
    branches: [ photo-management, main ]
  pull_request:
    branches: [ photo-management, main ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Analyze Flutter code
      run: flutter analyze
      
    - name: Run Flutter tests
      run: flutter test
      
    - name: Check Flutter formatting
      run: flutter format --dry-run --set-exit-if-changed .
