name: iOS Complete Build

on:
  push:
    branches: [ photo-management, main ]
  pull_request:
    branches: [ photo-management, main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
        cd ..
        
    - name: Build iOS app (Debug)
      run: |
        flutter build ios --debug --no-codesign
        
    - name: Build iOS app (Release)
      run: |
        flutter build ios --release --no-codesign
        
    - name: Archive iOS app
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -destination generic/platform=iOS -archivePath Runner.xcarchive archive
        
    - name: Export IPA
      run: |
        xcodebuild -exportArchive -archivePath ios/Runner.xcarchive -exportPath ios/build -exportOptionsPlist ios/ExportOptions.plist
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-ipa
        path: ios/build/*.ipa
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: |
          ios/build/
          build/
        retention-days: 7
