name: iOS Build (No Signing)

on:
  push:
    branches: [ photo-management, main ]
  pull_request:
    branches: [ photo-management, main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Clean iOS build artifacts
      run: |
        cd ios
        rm -rf Pods/
        rm -f Podfile.lock
        cd ..
        
    - name: Check iOS configuration
      run: |
        echo "Checking for Generated.xcconfig..."
        ls -la ios/Flutter/
        if [ -f "ios/Flutter/Generated.xcconfig" ]; then
          echo "Generated.xcconfig exists"
          cat ios/Flutter/Generated.xcconfig
        else
          echo "Generated.xcconfig not found, running flutter pub get again..."
          flutter pub get
          ls -la ios/Flutter/
        fi
        
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --repo-update
        cd ..
        
    - name: Fix script permissions
      run: |
        find ios/Pods -type f -name "*.sh" -exec chmod +x {} \;
        
    - name: Build iOS app (Debug)
      run: |
        flutter build ios --debug --no-codesign
        
    - name: Build iOS app (Release)
      run: |
        flutter build ios --release --no-codesign
        
    - name: List build outputs
      run: |
        echo "=== Debug Build Output ==="
        find build/ios -name "*.app" -type d
        echo "=== Release Build Output ==="
        find build/ios -name "*.app" -type d
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-files
        path: |
          build/ios/
        retention-days: 30
