name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
        cd ..
        
    - name: Build iOS app
      run: |
        flutter build ios --release --no-codesign
        
    - name: Archive iOS app
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -destination generic/platform=iOS -archivePath Runner.xcarchive archive
        
    - name: Export IPA
      run: |
        xcodebuild -exportArchive -archivePath ios/Runner.xcarchive -exportPath ios/build -exportOptionsPlist ios/ExportOptions.plist
        
    - name: Upload iOS Release
      uses: actions/upload-artifact@v4
      with:
        name: ios-release
        path: ios/build/*.ipa
        retention-days: 90

  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Build Android APK
      run: |
        flutter build apk --release
        
    - name: Build Android AAB
      run: |
        flutter build appbundle --release
        
    - name: Upload Android Release
      uses: actions/upload-artifact@v4
      with:
        name: android-release
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
        retention-days: 90
